import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare function toValue(value: string[]): number | number[];
export declare class Nouislider implements ControlValueAccessor, OnInit {
    private el: any;
    private behaviour: any;
    private connect: boolean[];
    private limit: any;
    private min: any;
    private max: any;
    private step: any;
    private config: any;
    private ngModel: any;
    private ngModelChange: any;
    private change: any;
    private update: any;
    private slide: any;
    private set: any;
    private start: any;
    private end: any;
    public slider: any;
    private value: any;
    private onChange: any;
    private onTouched: any;
    constructor(el: ElementRef);
    ngOnInit(): void;
    writeValue(value: any): void;
    registerOnChange(fn: (value: any) => void): void;
    registerOnTouched(fn: () => {}): void;
}
